# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180606_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.CharField(default=uuid.UUID('91e42336-d4fa-471b-a227-d63b12b57f6b'), max_length=40)),
            ],
        ),
    ]
